# Project-wide Gradle settings
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check the file buildSrc/src/main/kotlin/Android.kt in the repository

# When configured, Gradle will run in offline mode and will not attempt to
# access the network when running builds. Offline mode may be useful you don't
# have http access (behind a corporate firewall/VPN). Comment out this property
# to enable online mode.
org.gradle.offline=false

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable the new kotlin incremental compilation by default
kotlin.incremental=true

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include a dependency's R class.
# This property is useful if you are using alphas or betas of new libraries and you are
# getting multiple resource naming conflicts. This property will be removed in version 8.0 and
# all dependencies will use namespaced R classes by default.
android.nonTransitiveRClass=true

# org.gradle.java.home=path_to_jdk
